#cloning repo
git clone https://github.com/ayush7788/encoder.git

#installer script for Encoder
echo compiling library...
g++ -o lbry encoder/lib.cpp
echo compiling core...
g++ -o core encoder/main.cpp
echo linking objects...
g++ -o enc lbry core
echo installing...
mv enc /usr/bin/enc
echo Encoder has been installed.
